artifact_uri: file:///D:/Techflitter/House/mlruns_new/505120353686934126/1ce3ad73cf0d4eaf9e9d6abf52fa629d/artifacts
end_time: 1764758829253
entry_point_name: ''
experiment_id: '505120353686934126'
lifecycle_stage: active
run_id: 1ce3ad73cf0d4eaf9e9d6abf52fa629d
run_name: Random_Forest_run
run_uuid: 1ce3ad73cf0d4eaf9e9d6abf52fa629d
source_name: ''
source_type: 4
source_version: ''
start_time: 1764758822928
status: 3
tags: []
user_id: Sumanasri
