channels:
- conda-forge
dependencies:
- python=3.12.6
- pip<=25.3
- pip:
  - mlflow==2.14.1
  - cloudpickle==3.1.2
  - numpy==1.26.4
  - packaging==24.2
  - pandas==2.2.0
  - psutil==7.1.3
  - pyyaml==6.0.3
  - scikit-learn==1.5.2
  - scipy==1.14.1
name: mlflow-env
